services:
  # Frontend development server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: npm start

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - chromadb_data:/app/chromadb
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WEAVE_PROJECT_NAME=productivity-tracker
      - DEBUG=True
      - CHROMA_PERSIST_DIRECTORY=/app/chromadb
    env_file:
      - backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Production build (single container)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - chromadb_data:/app/chromadb
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WEAVE_PROJECT_NAME=productivity-tracker
      - CHROMA_PERSIST_DIRECTORY=/app/chromadb
    env_file:
      - backend/.env
    profiles:
      - production

volumes:
  chromadb_data:
    driver: local

networks:
  default:
    driver: bridge 